services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: lifeforge-db
    restart: unless-stopped
    env_file:
      - ./env/.env.docker
    environment:
      - DOCKER_MODE=true
      - PB_BINARY_PATH=/usr/local/bin/pocketbase
      - PB_DIR=/pb_data
    expose:
      - "8090"
    volumes:
      - ./database/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-init:
    build:
      context: .
      dockerfile: docker/db-init/Dockerfile
    container_name: lifeforge-db-init
    env_file:
      - ./env/.env.docker
    environment:
      - DOCKER_MODE=true
      - PB_DIR=/pb_data
      # Используем 0.0.0.0, так как init запускает свой сервер внутри себя
      - PB_HOST=http://0.0.0.0:8090
    volumes:
      # Только данные базы, код уже внутри образа
      - ./database/pb_data:/pb_data
    restart: "no"
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: lifeforge-server
    restart: unless-stopped
    env_file:
      - ./env/.env.docker
    environment:
      - CORS_ORIGIN=*
      - DOCKER_MODE=true
      - NODE_ENV=production
      # Сервер ходит к базе по сети
      - PB_HOST=http://db:8090
    expose:
      - "3636"
    # Volumes для кода больше не нужны!
    depends_on:
      # Ждем успешного завершения init
      db-init:
        condition: service_completed_successfully

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        # Убедитесь, что домен правильный
        - VITE_API_HOST=https://lifeforge-api.digitalkitty.ru
    container_name: lifeforge-client
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      server:
        condition: service_started
